apiVersion: v1
kind: Secret
metadata:
  name: maas-v2-client-api-secret
  labels:
    app: maas-v2-client-api
type: Opaque
stringData:
  DATABASE_URL: "mysql+aiomysql://user:password@mysql:3306/maas_v2"
  CH_DBT_USER: "bytehouse-user"
  CH_DBT_PASSWORD: "bytehouse-password"
  INTERNAL_API_KEY: "replace-with-internal-api-key"
